[package]
name = "todo-debug"
version = "0.0.1"
authors = [ "you",]
edition = "2018"

[dependencies.todo]
path = ".."

[dependencies.elrond-wasm]
version = "0.7.2"

[dependencies.elrond-wasm-debug]
version = "0.7.2"
